name: "Test"
on:
  workflow_dispatch:
jobs:
  build-icons:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v17
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: echo $NIX_PATH
    - run: sudo apt install wget
    - run: chmod +x ./collect_icons
    - run: ldd ./collect_icons
    
    - run: ./collect_icons
      shell: bash



