name: "Test"
on:
  workflow_dispatch:
jobs:
  build-icons:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v17
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: ldd ./collect_icons
    - run:   $(find /nix/store/ -name ld-linux-x86-64.so.2 -print -quit) ./collect_icons



