name: "Test"
on:
  workflow_dispatch:
jobs:
  build-icons:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v17
      with:
        nix_path: nixpkgs=https://nixos.org/channels/nixos-unstable
    - run: echo $NIX_PATH
    - run: nix-env -iA nixpkgs.openssl --option sandbox false
    - run:  LD_LIBRARY_PATH=$(find /nix/store/ -name libssl.so.1.1 -print -quit):$LD_LIBRARY_PATH   $(find /nix/store/ -name ld-linux-x86-64.so.2 -print -quit) ./collect_icons



