name: "Test"
on:
  workflow_dispatch:
jobs:
  compile-rust:
    runs-on: ubuntu-latest
    steps:
    - name: install Rust stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - run: ls /home
    - run: ls /home/runner
    - run: ls /home/runner/work
    - run: ls /home/runner/work/exp
    - run: ls /home/runner/work/exp/exp
    - run: cargo build --release
    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: target/release/nixos



