name: "Test"
on:
  workflow_dispatch:
jobs:
  compile-rust:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v17
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: workflow/nix-shell-action@v3
      with:
        packages: nixpkgs.openssl nixpkgs.cargo nixpkgs.gcc nixpkgs.rustc nixpkgs.pkgconfig
        script: cargo build --release




