name: "Test"
on:
  workflow_dispatch:
jobs:
  build-icons:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v17
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: echo $NIX_PATH
    - run: sudo apt install wget
    - run: chmod +x ./collect_icons
 
    - run:  LD_LIBRARY_PATH=$(find /nix/store/ -name libssl.so.1.1 -print -quit):$LD_LIBRARY_PATH   $(find /nix/store/ -name ld-linux-x86-64.so.2 -print -quit) ./collect_icons

      shell: bash



